typography_spectrum: 0.6523297
color:
  saturation: 0.6057348
  brandStrength: 0.9874552
  lightness: 0.125448
  brandColors:
    - '#82CBD2'
    - '#FFFFFF'
    - '#727272'
    - '#000000'
    - '#FFCD00'
  rhythmicContrast: 0.125448
layout_spectrum: 0.5179211
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a28b8b84-241a-4426-a2f5-6d493e15e35b.jpg
name: CapicuaTest
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/188641e9-4186-4a56-b342-c06cfdd369f5.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: >-
  We are a full stack creative hub that delivers Design, Development and Motion
  in one stop.
