collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6057348
  brandStrength: 0.9874552
  lightness: 0.125448
  brandColors:
    - '#82CBD2'
    - '#FFFFFF'
    - '#727272'
    - '#000000'
    - '#FFCD00'
  rhythmicContrast: 0.125448
typography_spectrum: 0.6523297
layout_spectrum: 0.5179211
name: CapicuaTest
